# Find contours

## Sources:
- [Contour Detection using OpenCV (Python/C++)](https://learnopencv.com/contour-detection-using-opencv-python-c/)

## Import modules

In [1]:
from pathlib import Path

import cv2
import numpy as np
import random ##toDo: use only numpy
from datetime import date

from utils.project_manager import Project
from utils.renderer.resizer import resize_with_pad, resize_with_crop


In [2]:
# create project
project = Project(project_dir="assets/images/find_contours")

## Read image

In [7]:
# read image
# img = cv2.imread('/Users/derrickvanfrausum/BeCode_AI/git-repos/learn-ai/opencv/assets/images/aviator-birds.png')
# img = cv2.imread('/Users/derrickvanfrausum/BeCode_AI/git-repos/coding-art/core/assets/images/mosaic/baba/db_baba/Erbil Zoo2.JPG')
# img = cv2.imread('/Users/derrickvanfrausum/BeCode_AI/git-repos/coding-art/core/assets/images/mosaic/baba/db_baba/Kotor.JPG')
# img = cv2.imread('/Users/derrickvanfrausum/BeCode_AI/git-repos/coding-art/core/assets/images/mosaic/baba/db_baba/Sveti Stefan near Budva.JPG')
# img = cv2.imread('/Users/derrickvanfrausum/BeCode_AI/git-repos/coding-art/core/assets/images/mosaic/baba/db_baba/bottle opener of Riyadh.JPG')
# img = cv2.imread('/Users/derrickvanfrausum/Downloads/pexels-abdullah-ghatasheh.jpg')
# img = cv2.imread('/Users/derrickvanfrausum/Downloads/dlf.pt-city-png-34153_lines.png')
img = cv2.imread('/Users/derrickvanfrausum/Downloads/pexels-aleksandar-pasaric-1530423.jpg')



## Find contours

In [8]:
# convert the image to grayscale format
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# invert image
# img_gray = cv2.bitwise_not(img_gray)

# apply binary thresholding
ret, thresh = cv2.threshold(img_gray, 180, 255, cv2.THRESH_BINARY) # 150, 255

# visualize the binary image
cv2.imshow('Binary image', thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [5]:
# convert the image to grayscale format
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# in this image, pixels in the silhoutte have all 26 (gray) as values => just replace these values by 255 (white)
img_gray[img_gray == 26] = 255
thresh = img_gray

In [19]:
img_gray

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0, 255, ..., 255, 255, 255],
       [  0,   0, 255, ..., 255, 255, 255],
       [  0,   0, 255, ..., 255, 255, 255]], dtype=uint8)

In [9]:
# detect the contours on the binary image using cv2.CHAIN_APPROX_NONE
# contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_NONE) # cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_SIMPLE) # cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
                                     
# draw contours on the original image
img_copy = img.copy()
img_copy = cv2.drawContours(image=img_copy, contours=contours, contourIdx=-1, color=(255, 0, 0), thickness=5, lineType=cv2.LINE_AA)
               
# see the results
cv2.imshow('None approximation', img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [31]:
hierarchy.shape

(1, 2, 4)

In [32]:
contours

[array([[[4259,    1]],
 
        [[4259,    9]],
 
        [[4258,   10]],
 
        ...,
 
        [[4264,   20]],
 
        [[4263,   19]],
 
        [[4263,    1]]], dtype=int32),
 array([[[3548, 1282]],
 
        [[3549, 1281]],
 
        [[3550, 1282]],
 
        [[3549, 1283]]], dtype=int32)]

In [11]:
img_copy = img.copy()
canvas = np.zeros_like(img)
isClosed = True
for cnt in contours:
    # cv2.fillPoly(img_copy, [cnt], (255, 0, 0))
    cv2.polylines(img_copy, [cnt], isClosed, (255, 0, 0), thickness=2, lineType=cv2.LINE_AA)
    cv2.polylines(canvas, [cnt], isClosed, (255, 0, 0), thickness=2, lineType=cv2.LINE_AA)

    # for point in cnt.reshape(-1, 2):
    #     x_px, y_px = point[0], point[1]

# see the results
cv2.imshow('fillPoly_img', img_copy)
cv2.imshow('fillPoly_canvas', canvas)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [40]:
cnt

array([[[1985,    0]],

       [[1985,    3]],

       [[1986,    4]],

       [[1986,   12]],

       [[1986,   11]],

       [[1987,   10]],

       [[1987,    1]],

       [[1986,    0]]], dtype=int32)

In [17]:
# see the results
cv2.imshow('fillPoly_dest_img', dest_img)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [13]:
img_copy = img.copy()
canvas = np.zeros_like(img)
isClosed = True
pts = []

contours_len = len(contours)
contour_indexes_selected = np.linspace(0, contours_len - 1, contours_len//100, dtype=int)

for cnt_idx in contour_indexes_selected:
    cnt = contours[cnt_idx]

# for cnt in contours:
    # cv2.fillPoly(img_copy, [cnt], (255, 0, 0))
    # cv2.polylines(img_copy, [cnt], isClosed, (255, 0, 0), thickness=2, lineType=cv2.LINE_AA)
    # cv2.polylines(canvas, [cnt], isClosed, (255, 0, 0), thickness=2, lineType=cv2.LINE_AA)

    # if contour has only a certain number of points, go directly to next iteration
    nb_points_threshold = 3
    if cnt.shape[0] != nb_points_threshold:
        continue

    points_array = cnt.reshape(-1, 2)
    points_array_len = len(points_array)
    point_indexes_selected = np.linspace(0, points_array_len - 1, max(points_array_len, nb_points_threshold), dtype=int)

    for point_idx in point_indexes_selected:
        point = points_array[point_idx]

    # for point in points_array:
        x_px, y_px = point[0], point[1]

        # draw circle on roi
        cv2.circle(img_copy, (x_px, y_px), 20, (0,0,255), thickness=-1)
        cv2.circle(canvas, (x_px, y_px), 20, (0,0,255), thickness=-1)

        pts.append([x_px, y_px])

pts = np.array(pts)
# polyline = pts.reshape((-1,1,2))

# cv2.polylines(img_copy, [polyline], isClosed, (255, 0, 0), thickness=50, lineType=cv2.LINE_AA)
# cv2.polylines(canvas, [polyline], isClosed, (255, 0, 0), thickness=50, lineType=cv2.LINE_AA)
# n = 971
# polylines = pts.reshape((len(pts)//(3*n),nb_points_threshold*n,2))
# cv2.polylines(img_copy, polylines, False, (255, 0, 0), thickness=5, lineType=cv2.LINE_AA)
# cv2.polylines(canvas, polylines, False, (255, 0, 0), thickness=5, lineType=cv2.LINE_AA)

for pt_i in pts:
    for pt_j in pts:
        if (pt_i != pt_j).all():
            pt_i = tuple(pt_i)
            pt_j = tuple(pt_j)
            cv2.line(img_copy, pt_i, pt_j, (255, 0, 0), thickness=2)
            cv2.line(canvas, pt_i, pt_j, (255, 0, 0), thickness=2)

# see the results
cv2.imshow('circles_img', img_copy)
cv2.imshow('circles_canvas', canvas)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [189]:
# listx = []
# listy=[]
                         
# for i in range(0, len(contours)):
#     cntr = contours[i]
#     size = cv2.contourArea(cntr)
#     if size < 1000:
#         M = cv2.moments(cntr)
#         cX = int(M["m10"] / (M["m00"] + 1e-5))
#         cY = int(M["m01"] / (M["m00"] + 1e-5))
#         listx.append(cX)
#         listy.append(cY)

# listxy = list(zip(listx,listy))
# listxy = np.array(listxy)

# for x1, y1 in listxy:    
#     distance = 0
#     secondx = []
#     secondy = []
#     dist_listappend = []
#     sort = []   
#     for x2, y2 in listxy:      
#         if (x1, y1) == (x2, y2):
#             pass     
#         else:
#             distance = np.sqrt((x1-x2)**2 + (y1-y2)**2)
#             secondx.append(x2)
#             secondy.append(y2)
#             dist_listappend.append(distance)               
#     secondxy = list(zip(dist_listappend,secondx,secondy))
#     sort = sorted(secondxy, key=lambda second: second[0])
#     sort = np.array(sort)
#     cv2.line(canvas, (x1,y1), (int(sort[0,1]), int(sort[0,2])), (0,0,255), 2)

# cv2.imwrite("connected.png", canvas)

KeyboardInterrupt: 

NameError: name 'listx' is not defined

In [190]:
cv2.imshow('circles_canvas', canvas)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

### try to center contour in middle of a square
dist = m - c
dist/2 = (m - nc)
dist/2 - m = - nc
m - dist/2 = nc
m - (m - c)/2 = nc

In [9]:
thickness = -1

factor = 0.5
# get new contours centered in the middle
m = img.shape[0]//2
new_contours = [(m - (m - contour)/factor).astype(np.uint) for contour in contours]

# draw contours on the original image
img_copy = img.copy()
img_copy = cv2.drawContours(image=img_copy, contours=new_contours, contourIdx=-1, color=(255, 0, 0), thickness=thickness, lineType=cv2.LINE_AA)
               
# see the results
cv2.imshow('None approximation', img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

## create gif

In [8]:
# import internal modules
# from typing import List, Set, Dict, TypedDict, Tuple, Optional, Union
# from pathlib import Path
from datetime import date


# import 3rd-party modules
import cv2
import numpy as np

# import local modules
from utils.renderer.giffer import create_gif
from utils.renderer.videographer import create_video
from utils.project_manager import Project

In [31]:
from utils.project_manager import Project

## Set up project

In [199]:
# name out img dirs
out_img_dir_list = ["bird", "bird_ij", "bird_ij_rotation", "bird_ij_color", "bird_ij_geomspace", "bird_ij_color_hsv"]

# create project
project = Project(project_dir="assets/images/find_contours", out_img_dir_list=out_img_dir_list)

In [32]:
# create project
project = Project(project_dir="assets/images/find_contours")

In [10]:
out_img_dir = "aviator_birds_ij_color"
project.make_dir(out_img_dir)

# get current date
today = date.today().strftime("%Y%m%d")

nb_images = 10000

canvas = np.zeros_like(img)

# rotation_range = np.arange(nb_images)

size_factors = np.linspace(0.01, 10, nb_images)
thickness = -1
m = img.shape[0]//2
# thickness_range = np.linspace(canvas.shape[0], 1, nb_images, dtype=np.uint64)

for i in range(0, nb_images):
    
    # get color
    color = np.random.randint(0,255, size=3, dtype=np.uint8).tolist()

    # get size factor
    size_factor = size_factors[i]   

    # # get thickness
    # thickness = thickness_range[i]

    # get new contours centered in the middle
    new_contours = [(m - (m - contour)/size_factor).astype(np.uint) for contour in contours]

    # draw contours on canvas
    canvas = cv2.drawContours(image=canvas, contours=new_contours, contourIdx=-1, color=color, thickness=thickness, lineType=cv2.LINE_AA)
    # canvas = cv2.drawContours(image=canvas, contours=contours, contourIdx=-1, color=color, thickness=thickness, lineType=cv2.LINE_AA)

    # # rotate canvas by 90°
    # canvas = np.rot90(canvas, rotation_range[i])

# set output image path
out_img_path = str(project.project_dir / f"{out_img_dir}_{nb_images}.jpg")

# save output image & metadata
cv2.imwrite(out_img_path, canvas)

True

In [101]:
out_img_dir = "bird"

# get current date
today = date.today().strftime("%Y%m%d")

nb_images = 60
canvas = np.zeros_like(img)

colors_range = np.linspace(0,255,num=nb_images, dtype=np.uint8)
colors = [[int(color), int(color), int(color)] for color in colors_range]

size_factors = np.linspace(0.01, 10, nb_images)
m = img.shape[0]//2
thickness = -1

for i in range(0, nb_images):

    # get color
    color = colors[i]

    # get size factor
    size_factor = size_factors[i]   

    # get new contours centered in the middle
    new_contours = [(m - (m - contour)/size_factor).astype(np.uint) for contour in contours]

    # draw contours on canvas
    canvas = cv2.drawContours(image=canvas, contours=new_contours, contourIdx=-1, color=color, thickness=thickness, lineType=cv2.LINE_AA)

    # set output image path
    out_img_path = str(project.out_img_dir_dict[out_img_dir] / f"{i:04d}.jpg")

    # save output image & metadata
    cv2.imwrite(out_img_path, canvas)

In [142]:
out_img_dir = "bird_ij_rotation"

# get current date
today = date.today().strftime("%Y%m%d")

nb_images = 60
canvas = np.zeros_like(img)

colors_range = np.linspace(0,255,num=nb_images, dtype=np.uint8)
colors = [[int(color), int(color), int(color)] for color in colors_range]

size_factors = np.linspace(0.01, 10, nb_images)
m = img.shape[0]//2
thickness = -1

rotation_range = np.arange(nb_images)

for i in range(0, nb_images):
    canvas = np.zeros_like(img)

    k = 0

    for j in range(nb_images-i,nb_images):

        # get color
        color = colors[j]

        # get size factor
        size_factor = size_factors[k]

        # get new contours centered in the middle
        new_contours = [(m - (m - contour)/size_factor).astype(np.uint) for contour in contours]

        # draw contours on canvas
        canvas = cv2.drawContours(image=canvas, contours=new_contours, contourIdx=-1, color=color, thickness=thickness, lineType=cv2.LINE_AA)

        k += 1

    # rotate canvas by 90°
    canvas = np.rot90(canvas, rotation_range[i])
    # set output image path
    out_img_path = str(project.out_img_dir_dict[out_img_dir] / f"{i:04d}.jpg")

    # save output image & metadata
    cv2.imwrite(out_img_path, canvas)

In [12]:
out_img_dir = "aviator_birds_ij_color"
project.make_dir(out_img_dir)

# get current date
today = date.today().strftime("%Y%m%d")

nb_images = 60

canvas = np.zeros_like(img)

rotation_range = np.arange(nb_images)

size_factors = np.linspace(0.01, 10, nb_images)
thickness = -1
m = img.shape[0]//2
# thickness_range = np.linspace(canvas.shape[0], 1, nb_images, dtype=np.uint64)

for i in range(0, nb_images):
    
    # get color
    color = np.random.randint(0,255, size=3, dtype=np.uint8).tolist()

    # get size factor
    size_factor = size_factors[i]   

    # # get thickness
    # thickness = thickness_range[i]

    # get new contours centered in the middle
    new_contours = [(m - (m - contour)/size_factor).astype(np.uint) for contour in contours]

    # draw contours on canvas
    canvas = cv2.drawContours(image=canvas, contours=new_contours, contourIdx=-1, color=color, thickness=thickness, lineType=cv2.LINE_AA)
    # canvas = cv2.drawContours(image=canvas, contours=contours, contourIdx=-1, color=color, thickness=thickness, lineType=cv2.LINE_AA)

    # # rotate canvas by 90°
    # canvas = np.rot90(canvas, rotation_range[i])

    # set output image path
    out_img_path = str(project.out_img_dir_dict[out_img_dir] / f"{i:04d}.jpg")

    # save output image & metadata
    cv2.imwrite(out_img_path, canvas)

In [246]:
out_img_dir = "bird_ij_geomspace"

# get current date
today = date.today().strftime("%Y%m%d")

nb_images = 60
canvas = np.zeros_like(img)

colors_range = np.geomspace(1,255,num=nb_images, dtype=np.uint8)
colors = [[int(color), int(color), int(color)] for color in colors_range]

size_factors = np.geomspace(0.01, 10, nb_images)
m = img.shape[0]//2
thickness = -1

# rotation_range = np.arange(nb_images)

for i in range(0, nb_images):
    canvas = np.zeros_like(img)

    k = 0

    for j in range(nb_images-i,nb_images):

        # get color
        color = colors[j]

        # get size factor
        size_factor = size_factors[k]

        # get new contours centered in the middle
        new_contours = [(m - (m - contour)/size_factor).astype(np.uint) for contour in contours]

        # draw contours on canvas
        canvas = cv2.drawContours(image=canvas, contours=new_contours, contourIdx=-1, color=color, thickness=thickness, lineType=cv2.LINE_AA)

        k += 1

    # # rotate canvas by 90°
    # canvas = np.rot90(canvas, rotation_range[i])
    # set output image path
    out_img_path = str(project.out_img_dir_dict[out_img_dir] / f"{i:04d}.jpg")

    # save output image & metadata
    cv2.imwrite(out_img_path, canvas)

In [242]:
out_img_dir = "bird_ij_color_hsv"

# get current date
today = date.today().strftime("%Y%m%d")

nb_images = 60
nb_draw_contours = 20
steps = nb_images*nb_draw_contours

# colors_range = np.linspace(0,255,num=nb_images, dtype=np.uint8)
# colors = [[int(color), int(color), int(color)] for color in colors_range]

# H: 0-179, S: 0-255, V: 0-255
# hue_range = np.geomspace(1,179,num=nb_images, dtype=np.uint8)
saturation = 255
value = 255

size_factors = np.geomspace(0.01, 100, steps)
m = img.shape[0]//2
thickness = -1

# rotation_range = np.arange(nb_images)

for i in range(0, steps):
    canvas = np.zeros_like(img)

    for j in range(i):

        # # get color
        # color = np.random.randint(0,255, size=3, dtype=np.uint8).tolist()
        color = cv2.cvtColor(np.array([[[np.random.randint(0,179, dtype=np.uint8), saturation, value]]], dtype=np.uint8), cv2.COLOR_HSV2BGR).reshape(-1).tolist()

        # get size factor
        size_factor = size_factors[j]

        # get new contours centered in the middle
        new_contours = [(m - (m - contour)/size_factor).astype(np.uint) for contour in contours]

        # draw contours on canvas
        canvas = cv2.drawContours(image=canvas, contours=new_contours, contourIdx=-1, color=color, thickness=thickness, lineType=cv2.LINE_AA)


    # # rotate canvas by 90°
    # canvas = np.rot90(canvas, rotation_range[i])

    if i%nb_images == 0:
        # set output image path
        out_img_path = str(project.out_img_dir_dict[out_img_dir] / f"{i:04d}.jpg")

        # save output image & metadata
        cv2.imwrite(out_img_path, canvas)

In [15]:
out_img_dir = "bird_ij_color_steps"
project.make_dir(out_img_dir)

# get current date
today = date.today().strftime("%Y%m%d")

nb_images = 60
nb_draw_contours = 20
steps = nb_images*nb_draw_contours

# colors_range = np.geomspace(1,255,num=steps, dtype=np.uint8)
# colors = [[int(color), int(color), int(color)] for color in colors_range]

size_factors = np.linspace(0.01, 10, steps)
m = img.shape[0]//2
thickness = -1

# rotation_range = np.arange(nb_images)

for i in range(0, steps):
    canvas = np.zeros_like(img)

    for j in range(i):
    
        # get color
        color = np.random.randint(0,255, size=3, dtype=np.uint8).tolist()

        # get size factor
        size_factor = size_factors[j]  

        # get new contours centered in the middle
        new_contours = [(m - (m - contour)/size_factor).astype(np.uint) for contour in contours]

        # draw contours on canvas
        canvas = cv2.drawContours(image=canvas, contours=new_contours, contourIdx=-1, color=color, thickness=thickness, lineType=cv2.LINE_AA)

        # # rotate canvas by 90°
        # canvas = np.rot90(canvas, rotation_range[i])

    if i%nb_images == 0:
        # set output image path
        out_img_path = str(project.out_img_dir_dict[out_img_dir] / f"{i:04d}.jpg")

        # save output image & metadata
        cv2.imwrite(out_img_path, canvas)

In [ ]:
# get img height & width
dest_img_height, dest_img_width = canvas.shape[:2]

# set gif path
gif_path = project.project_dir / f"{out_img_dir}.gif"

# create gif
create_gif(img_dir=project.out_img_dir_dict[out_img_dir], out_path=gif_path, out_img_shape=(int(dest_img_height//4.2),int(dest_img_width//4.2)),
sort_img_list=True, reverse_img_list=True, duplicate_start_img_amount=0, duplicate_end_img_amount=0)

https://newbedev.com/determine-if-a-point-is-inside-or-outside-of-a-shape-with-opencv
In the function, the third argument is measureDist. If it is True, it finds the shortest distance between a point in the image and a contour. If False, it finds whether the point is inside, outside, or on the contour.

In [10]:
out_img_dir = "voronoi"
project.make_dir(out_img_dir)

In [11]:
points = []

points_by_contour = []

for cnt in contours:
    # points = []

    points_array = cnt.reshape(-1, 2)
    points_array_len = len(points_array)
    point_indexes_selected = np.linspace(0, points_array_len - 1, min(points_array_len, 100), dtype=int)

    for point_idx in point_indexes_selected:
        point = points_array[point_idx]

        x_px, y_px = point[0], point[1]
        points.append((x_px, y_px))
    
    # points_by_contour.append(points)

In [12]:

nb_points = 1000

points_inside_contours = []

points_inside_contours_by_contour = []

while len(points_inside_contours) < nb_points:
    for i, cnt in enumerate(contours):
        # points_inside_contours = []
        # get random point
        point = (np.random.randint(0,img.shape[1]), np.random.randint(0,img.shape[0]))
        result = cv2.pointPolygonTest(cnt, point, False)
        # if result is inside (== 1) # 0: contour, -1: outside
        if result == 1:
            points_inside_contours.append(point)
            continue

        # points_by_contour[i].append(points_inside_contours)

# for points in points_by_contour:
#     points = list(set(points))

# # add points_inside_contours to set of contours
# points.extend(points_inside_contours)

# remove any duplicates
points = list(set(points))

In [13]:
# Check if a point is inside a rectangle
def rect_contains(rect, point) :
    if point[0] < rect[0] :
        return False
    elif point[1] < rect[1] :
        return False
    elif point[0] > rect[2] :
        return False
    elif point[1] > rect[3] :
        return False
    return True

# Draw a point
def draw_point(img, p, color ) :
    cv2.circle( img, p, 2, color, cv2.FILLED, cv2.LINE_AA, 0 )

# Draw delaunay triangles
def draw_delaunay(img, subdiv, delaunay_color) :

    triangleList = subdiv.getTriangleList();
    size = img.shape
    r = (0, 0, size[1], size[0])

    for t in triangleList :

        pt1 = (t[0], t[1])
        pt2 = (t[2], t[3])
        pt3 = (t[4], t[5])

        if rect_contains(r, pt1) and rect_contains(r, pt2) and rect_contains(r, pt3) :

            cv2.line(img, pt1, pt2, delaunay_color, 1, cv2.LINE_AA, 0)
            cv2.line(img, pt2, pt3, delaunay_color, 1, cv2.LINE_AA, 0)
            cv2.line(img, pt3, pt1, delaunay_color, 1, cv2.LINE_AA, 0)

# Draw voronoi diagram
def draw_voronoi(img, subdiv) :

    ( facets, centers) = subdiv.getVoronoiFacetList([])

    for i in range(0,len(facets)) :
        ifacet_arr = []
        for f in facets[i] :
            ifacet_arr.append(f)

        ifacet = np.array(ifacet_arr, int)
        color = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))

        cv2.fillConvexPoly(img, ifacet, color, cv2.LINE_AA, 0);
        ifacets = np.array([ifacet])
        cv2.polylines(img, ifacets, True, (0, 0, 0), 1, cv2.LINE_AA, 0)
        cv2.circle(img, (centers[i][0], centers[i][1]), 3, (0, 0, 0), cv2.FILLED, cv2.LINE_AA, 0)

# Draw voronoi diagram
def draw_voronoi_masks(ref_img_shape, subdiv, img_path_list) :

    ( facets, centers) = subdiv.getVoronoiFacetList([])

    out_img = np.zeros(ref_img_shape, dtype = np.uint8)

    error_count = 0

    for i in range(0,len(facets)) :

        mask = np.zeros(ref_img_shape[:2], dtype = np.uint8)
        canvas = np.zeros(ref_img_shape, dtype = np.uint8)

        ref_img_height, ref_img_width, ref_img_channel = ref_img_shape

        global ifacet
        
        ifacet_arr = []
        for f in facets[i] :
            ifacet_arr.append(f)

        ifacet = np.array(ifacet_arr, int)
        color = 1

        cv2.fillConvexPoly(mask, ifacet, color, cv2.LINE_AA, 0);
        ifacets = np.array([ifacet])
        # cv2.polylines(out_img, ifacets, True, (0, 0, 0), 3, cv2.LINE_AA, 0)
        # cv2.circle(mask, (centers[i][0], centers[i][1]), 3, 0, cv2.FILLED, cv2.LINE_AA, 0)

        # img = resize_with_crop(img_path = img_path_list[i], ref_img_shape = ref_img_shape)
        #  img = cv2.bitwise_and(img, img, mask=mask)

        # resize to bbox shape
        bbox = bounding_box(ifacet)
        bbox_shape = (bbox[1] - bbox[0], bbox[3] - bbox[2])

        try:
            img = resize_with_crop(img_path = img_path_list[i], ref_img_shape = (bbox_shape[0], bbox_shape[1], 3))

             # put img to bbox position, clip img if bbox falls outside of canvas
            clip_amount_min_y = 0 - bbox[0] if bbox[0] < 0 else 0
            clip_amount_min_x = 0 - bbox[2] if bbox[2] < 0 else 0
            clip_amount_max_y = ref_img_height - bbox[1] if bbox[1] > ref_img_height else 0
            clip_amount_max_x = ref_img_width - bbox[3] if bbox[3] > ref_img_width else 0
            # print(bbox[0], clip_amount_min_y, bbox[1], clip_amount_max_y)
            # print(bbox[2], clip_amount_min_x, bbox[3], clip_amount_max_x)
            # print(clip_amount_min_y, bbox_shape[0], clip_amount_max_y)
            # print(clip_amount_min_x, bbox_shape[1], clip_amount_max_x)

            canvas[
                bbox[0] + clip_amount_min_y:bbox[1] + clip_amount_max_y, 
                bbox[2] + clip_amount_min_x:bbox[3] + clip_amount_max_x, 
                :] = img[
                clip_amount_min_y:bbox_shape[0] + clip_amount_max_y, 
                clip_amount_min_x:bbox_shape[1] + clip_amount_max_x
                , :]
            
            img = cv2.bitwise_and(canvas, canvas, mask=mask)

        except:
            # img = np.ones((bbox_shape[0], bbox_shape[1], 3), dtype=np.uint8)
            img = resize_with_crop(img_path = img_path_list[i], ref_img_shape = ref_img_shape)
            img = cv2.bitwise_and(img, img, mask=mask)

            error_count += 1
            print("error_count:", error_count)
            print("bbox:", bbox)
            print("bbox_shape:", bbox_shape)

       
       
        out_img = cv2.add(out_img, img)

    return out_img


def bounding_box(points):
    x_coordinates, y_coordinates = zip(*points)

    return [min(y_coordinates), max(y_coordinates), min(x_coordinates), max(x_coordinates)]

In [14]:
# Define window names
win_delaunay = "Delaunay Triangulation"
win_voronoi = "Voronoi Diagram"

# Turn on animation while drawing triangles
animate = True

# Define colors for drawing.
delaunay_color = (255,255,255)
points_color = (0, 0, 255)

# # Read in the image.
# img = cv2.imread("image.jpg");
# img = np.ones((500, 1000, 3), dtype=np.uint8)*255
# img = np.zeros((3888, 5184, 3), dtype=np.uint8)

# img = cv2.imread("assets/images/mosaic/snapshots/spiderman/to_recreate/spiderman_window.png")

# Keep a copy around
img_orig = img.copy();

# Rectangle to be used with Subdiv2D
size = img.shape
rect = (0, 0, size[1], size[0])

# Create an instance of Subdiv2D
subdiv = cv2.Subdiv2D(rect);

# # Create an array of points.
# points = [];

# # Read in the points from a text file
# with open("points.txt") as file :
#     for line in file :
#         x, y = line.split()
#         points.append((int(x), int(y)))

# NB_POINTS = len(img_path_list)
# ys = np.random.randint(0, size[0], size=(NB_POINTS,), dtype=int)
# xs = np.random.randint(0, size[1], size=(NB_POINTS,), dtype=int)


# points = list(zip(xs, ys))

# Insert points into subdiv
for points in points_by_contour:
    for p in points :
        subdiv.insert(p)

        # Show animation
        if animate :
            img_copy = img_orig.copy()
            # Draw delaunay triangles
            draw_delaunay( img_copy, subdiv, (255, 255, 255) );
            cv2.imshow(win_delaunay, img_copy)
            cv2.waitKey(50)
            
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

# # Draw delaunay triangles
# draw_delaunay( img, subdiv, (255, 255, 255) );

# Draw points
# for p in points :
#     draw_point(img, p, (0,0,255))

# # Allocate space for Voronoi Diagram
# img_voronoi = np.zeros_like(img)

# Draw Voronoi diagram
# draw_voronoi(img_voronoi,subdiv)
# out_img = draw_voronoi_masks(tuple(img.shape), subdiv, img_path_list)

# # get current date
# today = date.today().strftime("%Y%m%d")

# # set output image path
# out_img_path = str(project.out_img_dir_dict[out_img_dir] / f"{NB_POINTS}_{today}.jpg")

# # save output image
# cv2.imwrite(out_img_path, out_img)

# Show results
# cv2.imshow(win_delaunay,img)
# cv2.imshow(win_voronoi,img_voronoi)
# cv2.imshow(win_voronoi, out_img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# cv2.waitKey(1)


# Allocate space for Voronoi Diagram
img_voronoi = np.zeros_like(img)

# Draw Voronoi diagram
draw_voronoi(img_voronoi,subdiv)

# mask
out_img = cv2.bitwise_and(img_voronoi, img_voronoi, mask=img_gray)

# get current date
today = date.today().strftime("%Y%m%d")

# set output image path
out_img_path = str(project.out_img_dir_dict[out_img_dir] / f"voronoi_{nb_points}_{today}.jpg")

# save output image
cv2.imwrite(out_img_path, out_img)

# Show results
cv2.imshow(win_voronoi,out_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

In [19]:
# Allocate space for Voronoi Diagram
img_voronoi = np.zeros_like(img)

# Draw Voronoi diagram
draw_voronoi(img_voronoi,subdiv)

# mask
out_img = cv2.bitwise_and(img_voronoi, img_voronoi, mask=img_gray)

# get current date
today = date.today().strftime("%Y%m%d")

# set output image path
out_img_path = str(project.out_img_dir_dict[out_img_dir] / f"voronoi_{nb_points}_{today}.jpg")

# save output image
cv2.imwrite(out_img_path, out_img)

# Show results
cv2.imshow(win_voronoi,out_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

<ipython-input-7-9da3d9c1b5af>:52: DeprecationWarning: an integer is required (got type numpy.float32).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  cv2.circle(img, (centers[i][0], centers[i][1]), 3, (0, 0, 0), cv2.FILLED, cv2.LINE_AA, 0)


-1

## Save delaunay triangles

In [ ]:
triangleList = subdiv.getTriangleList()

text_file_path = "assets/data/delaunay_triangles.txt"
with open(text_file_path, "w") as f:
    for t in triangleList: 
        # pt1 = (t[0], t[1])
        # pt2 = (t[2], t[3])
        # pt3 = (t[4], t[5])

        f.writelines(f"{str(list(t))}\n")
        # f.writelines(str(list(t)))

triangles = []
#open and read the file:
with open(text_file_path, "r") as f:
    lines = f.readlines()
    
for line in lines:
    line = line.strip('][]\n').split(', ')
    triangle = [float(nb) for nb in line]
    triangles.append(triangle)
    

## Save Voronoi faces

In [ ]:
triangleList = subdiv.getTriangleList()

text_file_path = "assets/data/delaunay_triangles.txt"
with open(text_file_path, "w") as f:
    for t in triangleList: 
        # pt1 = (t[0], t[1])
        # pt2 = (t[2], t[3])
        # pt3 = (t[4], t[5])

        f.writelines(f"{str(list(t))}\n")
        # f.writelines(str(list(t)))

triangles = []
#open and read the file:
with open(text_file_path, "r") as f:
    lines = f.readlines()
    
for line in lines:
    line = line.strip('][]\n').split(', ')
    triangle = [float(nb) for nb in line]
    triangles.append(triangle)
    

In [ ]:
( facets, centers) = subdiv.getVoronoiFacetList([])

for i in range(0,len(facets)) :
    ifacet_arr = []
    for f in facets[i] :
        ifacet_arr.append(f)

    ifacet = np.array(ifacet_arr, int)
    color = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))

    cv2.fillConvexPoly(img, ifacet, color, cv2.LINE_AA, 0);
    ifacets = np.array([ifacet])
    cv2.polylines(img, ifacets, True, (0, 0, 0), 1, cv2.LINE_AA, 0)
    cv2.circle(img, (centers[i][0], centers[i][1]), 3, (0, 0, 0), cv2.FILLED, cv2.LINE_AA, 0)


In [21]:
( facets, centers) = subdiv.getVoronoiFacetList([])

In [22]:
facets[3].shape

(6, 2)

In [ ]:
def remove_from_contour(contour, defectsIdx, tmp):
    minDist = sys.maxsize
    startIdx, endIdx = 0, 0

    for i in range(0,len(defectsIdx)):
        for j in range(i+1, len(defectsIdx)):
            dist = ed2(contour[defectsIdx[i]][0], contour[defectsIdx[j]][0])
            if minDist > dist:
                minDist = dist
                startIdx = defectsIdx[i]
                endIdx = defectsIdx[j]

    if startIdx <= endIdx:
        inside = contour[startIdx:endIdx]
        len1 = 0 if inside.size == 0 else cv2.arcLength(inside, False)
        outside1 = contour[0:startIdx]
        outside2 = contour[endIdx:len(contour)]
        len2 = (0 if outside1.size == 0 else cv2.arcLength(outside1, False)) + (0 if outside2.size == 0 else cv2.arcLength(outside2, False))
        if len2 < len1:
            startIdx,endIdx = endIdx,startIdx     
    else:
        inside = contour[endIdx:startIdx]
        len1 = 0 if inside.size == 0 else cv2.arcLength(inside, False)
        outside1 = contour[0:endIdx]
        outside2 = contour[startIdx:len(contour)]
        len2 = (0 if outside1.size == 0 else cv2.arcLength(outside1, False)) + (0 if outside2.size == 0 else cv2.arcLength(outside2, False))
        if len1 < len2:
            startIdx,endIdx = endIdx,startIdx

    if startIdx <= endIdx:
        out = np.concatenate((contour[0:startIdx], contour[endIdx:len(contour)]), axis=0)
    else:
        out = contour[endIdx:startIdx]
    return out


def remove_defects(mask, debug=False):
    tmp = mask.copy()
    mask = cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY)

    # get contour
    contours, _ = cv2.findContours(
        mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    assert len(contours) > 0, "No contours found"
    contour = sorted(contours, key=cv2.contourArea)[-1] #largest contour
    if debug:
        init = cv2.drawContours(tmp.copy(), [contour], 0, (255, 0, 255), 1, cv2.LINE_AA)
        figure, ax = plt.subplots(1)
        ax.imshow(init)
        ax.set_title("Initital Contour")

    hull = cv2.convexHull(contour, returnPoints=False)
    defects = cv2.convexityDefects(contour, hull)

    while True:
        defectsIdx = []
        
        for i in range(defects.shape[0]):
            s, e, f, d = defects[i, 0]
            start = tuple(contour[s][0])
            end = tuple(contour[e][0])
            far = tuple(contour[f][0])
            
            depth = d / 256
            if depth > 2:
                defectsIdx.append(f)

        if len(defectsIdx) < 2:
            break

        contour = remove_from_contour(contour, defectsIdx, tmp)
        hull = cv2.convexHull(contour, returnPoints=False)
        defects = cv2.convexityDefects(contour, hull)

    if debug:
      rslt = cv2.drawContours(tmp.copy(), [contour], 0, (0, 255, 255), 1)
      figure, ax = plt.subplots(1)
      ax.imshow(rslt)
      ax.set_title("Corrected Contour")

mask = cv2.imread("a.png")
remove_defects(mask, True)

## Find and draw contours with colors from another picture 

In [ ]:
img = cv2.imread('/Users/derrickvanfrausum/Downloads/pexels-aleksandar-pasaric-1530423.jpg')
img = resize_with_crop(img, ref_img_shape=(img.shape[0]//5, img.shape[1]//5, 3))

# convert the image to grayscale format
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# invert image
# img_gray = cv2.bitwise_not(img_gray)

# apply binary thresholding
ret, thresh = cv2.threshold(img_gray, 180, 255, cv2.THRESH_BINARY) # 150, 255

# detect the contours on the binary image using cv2.CHAIN_APPROX_NONE
# contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_NONE) # cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_SIMPLE) # cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)


img_copy = img.copy()
canvas = np.zeros_like(img_copy)
dest_img_path = Path("/Users/derrickvanfrausum/Pictures/Adobe Lightroom/P2233204.jpg")
dest_img = cv2.imread(str(dest_img_path))
dest_img = resize_with_pad(dest_img, ref_img=img_copy)

for cnt in contours:
    mask = np.zeros((img_copy.shape[0], img_copy.shape[1]), dtype=np.uint8)
    # mask = cv2.drawContours(mask, [cnt], -1, 1, -1)
    mask = cv2.fillPoly(mask, [cnt], 1)
    roi = cv2.bitwise_and(dest_img, dest_img, mask=mask)
    roi = roi[mask > 0]

    color = np.mean(roi, axis=0)

    # cv2.drawContours(canvas, [cnt], -1, color, -1)
    cv2.fillPoly(canvas, [cnt], color)
    # cv2.fillPoly(dest_img, [cnt], color)
    # cv2.fillPoly(img_copy, [cnt], (255, 0, 0))

# get current date
today = date.today().strftime("%Y%m%d")

# set output image path
out_img_path = str(f"{dest_img_path.stem}_{today}_roi_mean.jpg")

# save output image
# cv2.imwrite(out_img_path, canvas)
cv2.imwrite(out_img_path, dest_img)

# # see the results
# cv2.imshow('fillPoly_dest_img', dest_img)

# cv2.waitKey(0)
# cv2.destroyAllWindows()
# cv2.waitKey(1)


In [123]:
img = cv2.imread('/Users/derrickvanfrausum/Pictures/raindrop.png')
dest_img_path = Path("/Users/derrickvanfrausum/Pictures/Adobe Lightroom/P2233204.jpg")
dest_img = cv2.imread(str(dest_img_path))
# dest_img = resize_with_pad(dest_img, ref_img=img_copy)
img = resize_with_crop(img, ref_img_shape=(dest_img.shape[0], dest_img.shape[1], 3))

# convert the image to grayscale format
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# invert image
# img_gray = cv2.bitwise_not(img_gray)

# apply binary thresholding
ret, thresh = cv2.threshold(img_gray, 180, 255, cv2.THRESH_BINARY) # 150, 255

# detect the contours on the binary image using cv2.CHAIN_APPROX_NONE
# contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_NONE) # cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_SIMPLE) # cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)


img_copy = img.copy()
canvas = np.zeros_like(img_copy)


for cnt in contours[1:3]:
    mask = np.zeros((img_copy.shape[0], img_copy.shape[1]), dtype=np.uint8)
    # mask = cv2.drawContours(mask, [cnt], -1, 1, -1)
    mask = cv2.fillPoly(mask, [cnt], 1)
    roi = cv2.bitwise_and(dest_img, dest_img, mask=mask)
    roi = roi[mask > 0]

    color = np.mean(roi, axis=0)

    # cv2.drawContours(canvas, [cnt], -1, color, -1)
    cv2.fillPoly(dest_img, [cnt], color)
    # cv2.fillPoly(img_copy, [cnt], (255, 0, 0))

# get current date
today = date.today().strftime("%Y%m%d")

# set output image path
out_img_path = str(f"{dest_img_path.stem}_{today}_roi_mean.jpg")

# save output image
cv2.imwrite(out_img_path, dest_img)

# # see the results
# cv2.imshow('fillPoly_dest_img', dest_img)

# cv2.waitKey(0)
# cv2.destroyAllWindows()
# cv2.waitKey(1)


True

In [74]:
hierarchy

array([[[ 1, -1, -1, -1],
        [ 2,  0, -1, -1],
        [-1,  1, -1, -1]]], dtype=int32)

In [78]:
len(contours)

3

In [90]:
print(contours[0])

[[[772 103]]

 [[771 104]]

 [[770 104]]

 ...

 [[777 108]]

 [[777 105]]

 [[775 103]]]


In [122]:
contours[0][:,0,0].max()

100

In [101]:
def normalize_between_range(xs, a, b):
    """
    Function to normalize a series between range [a,b]
    """
    min_x = np.min(xs)
    max_x = np.max(xs)
    return (b - a) * (xs - min_x)/(max_x - min_x) + a

In [125]:
normalize_between_range(contours[0][:,0,0], 0, 1)*100

array([50.        , 49.92657856, 49.85315712, ..., 50.3671072 ,
       50.3671072 , 50.22026432])

In [133]:
cnt = np.empty(contours[0].shape)
cnt[:,0,0] = normalize_between_range(contours[0][:,0,0], 0, 1)
cnt[:,0,1] = normalize_between_range(contours[0][:,0,1], 0, 1)

In [135]:
np.save("raindrop_contours.npy", cnt)

In [129]:
img = cv2.imread('/Users/derrickvanfrausum/Pictures/raindrop.png')
dest_img_path = Path("/Users/derrickvanfrausum/Pictures/Adobe Lightroom/P2233204.jpg")
dest_img = cv2.imread(str(dest_img_path))
# dest_img = resize_with_pad(dest_img, ref_img=img_copy)
img = resize_with_crop(img, ref_img_shape=(dest_img.shape[0], dest_img.shape[1], 3))

img_copy = img.copy()
canvas = np.zeros_like(img_copy)


mask = np.zeros((img_copy.shape[0], img_copy.shape[1]), dtype=np.uint8)
# mask = cv2.drawContours(mask, [cnt], -1, 1, -1)
mask = cv2.fillPoly(mask, [cnt], 1)
roi = cv2.bitwise_and(dest_img, dest_img, mask=mask)
roi = roi[mask > 0]

color = np.mean(roi, axis=0)

# cv2.drawContours(canvas, [cnt], -1, color, -1)
cv2.fillPoly(dest_img, [cnt], color, lineType=cv2.LINE_AA)
# cv2.fillPoly(img_copy, [cnt], (255, 0, 0))

# get current date
today = date.today().strftime("%Y%m%d")

# set output image path
out_img_path = str(f"{dest_img_path.stem}_{today}_roi_mean_normalized.jpg")

# save output image
cv2.imwrite(out_img_path, dest_img)

# # see the results
# cv2.imshow('fillPoly_dest_img', dest_img)

# cv2.waitKey(0)
# cv2.destroyAllWindows()
# cv2.waitKey(1)


True

In [121]:
contours[0][:,0,1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [134]:
cnt

array([[[0.5       , 0.        ]],

       [[0.49926579, 0.00052165]],

       [[0.49853157, 0.00052165]],

       ...,

       [[0.50367107, 0.00260824]],

       [[0.50367107, 0.0010433 ]],

       [[0.50220264, 0.        ]]])

In [141]:
pts = np.empty(cnt.shape)
pts[:,0,0] = cnt[:,0,0]*20*1000 + 1
pts[:,0,1] = cnt[:,0,1]*20*1000 + 1
pts = pts.astype(int)
pts 

array([[[10001,     1]],

       [[ 9986,    11]],

       [[ 9971,    11]],

       ...,

       [[10074,    53]],

       [[10074,    21]],

       [[10045,     1]]])

In [143]:
def cart2pol(x, y):
    theta = np.arctan2(y, x)
    rho = np.hypot(x, y)
    return theta, rho


def pol2cart(theta, rho):
    x = rho * np.cos(theta)
    y = rho * np.sin(theta)
    return x, y


def rotate_contour(cnt, angle):
    M = cv2.moments(cnt)
    cx = int(M['m10']/M['m00'])
    cy = int(M['m01']/M['m00'])

    cnt_norm = cnt - [cx, cy]
    
    coordinates = cnt_norm[:, 0, :]
    xs, ys = coordinates[:, 0], coordinates[:, 1]
    thetas, rhos = cart2pol(xs, ys)
    
    thetas = np.rad2deg(thetas)
    thetas = (thetas + angle) % 360
    thetas = np.deg2rad(thetas)
    
    xs, ys = pol2cart(thetas, rhos)
    
    cnt_norm[:, 0, 0] = xs
    cnt_norm[:, 0, 1] = ys

    cnt_rotated = cnt_norm + [cx, cy]
    cnt_rotated = cnt_rotated.astype(np.int32)

    return cnt_rotated

def scale_contour(cnt, scale):
    M = cv2.moments(cnt)
    cx = int(M['m10']/M['m00'])
    cy = int(M['m01']/M['m00'])

    cnt_norm = cnt - [cx, cy]
    cnt_scaled = cnt_norm * scale
    cnt_scaled = cnt_scaled + [cx, cy]
    cnt_scaled = cnt_scaled.astype(np.int32)

    return cnt_scaled

In [147]:
img = cv2.imread('/Users/derrickvanfrausum/Pictures/raindrop.png')
dest_img_path = Path("/Users/derrickvanfrausum/Pictures/Adobe Lightroom/P2233204.jpg")
dest_img = cv2.imread(str(dest_img_path))
# dest_img = resize_with_pad(dest_img, ref_img=img_copy)
img = resize_with_crop(img, ref_img_shape=(dest_img.shape[0], dest_img.shape[1], 3))

# convert the image to grayscale format
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# invert image
# img_gray = cv2.bitwise_not(img_gray)

# apply binary thresholding
ret, thresh = cv2.threshold(img_gray, 180, 255, cv2.THRESH_BINARY) # 150, 255

# detect the contours on the binary image using cv2.CHAIN_APPROX_NONE
# contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_NONE) # cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_SIMPLE) # cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)


img_copy = img.copy()
canvas = np.zeros_like(img_copy)

cnt = contours[0]

for i in range(1000):

    cnt_rotated = rotate_contour(cnt, -30)
    cnt_scaled = scale_contour(cnt_rotated, np.random.random() * 0.1)
    
    cnt_translated = cnt_scaled + np.random.randint(low=-2000, high=2000, size=(2,))

    mask = np.zeros((img_copy.shape[0], img_copy.shape[1]), dtype=np.uint8)
    # mask = cv2.drawContours(mask, [cnt], -1, 1, -1)
    mask = cv2.fillPoly(mask, [cnt_translated], 1)
    roi = cv2.bitwise_and(dest_img, dest_img, mask=mask)
    roi = roi[mask > 0]

    color = np.mean(roi, axis=0)

    # cv2.drawContours(canvas, [cnt], -1, color, -1)
    cv2.fillPoly(dest_img, [cnt_translated], color)
    # cv2.fillPoly(img_copy, [cnt], (255, 0, 0))

# get current date
today = date.today().strftime("%Y%m%d")

# set output image path
out_img_path = str(f"{dest_img_path.stem}_{today}_roi_mean_rot.jpg")

# save output image
cv2.imwrite(out_img_path, dest_img)

# # see the results
# cv2.imshow('fillPoly_dest_img', dest_img)

# cv2.waitKey(0)
# cv2.destroyAllWindows()
# cv2.waitKey(1)


True

: 